version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
  before_build:
    - cp -r docs/_static/api-reference output/html/_static/api-reference

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

# Explicitly set the version of Python and its requirements
python:
  install:
    - requirements: docs/requirements.txt
