sudo: required
cache: bundler

language: ruby

rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.5
  - 2.6.2

gemfile:
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
  - gemfiles/active_record_5.1.gemfile
  - gemfiles/active_record_5.2.gemfile

env:
  - PREPARED_STATEMENTS=0
  - PREPARED_STATEMENTS=1

matrix:
  fast_finish: true
  exclude:
    - rvm: 2.3.8
      gemfile: gemfiles/rails_6.0.gemfile
    - rvm: 2.4.5
      gemfile: gemfiles/rails_4.0.gemfile
    - rvm: 2.4.5
      gemfile: gemfiles/rails_4.1.gemfile
    - rvm: 2.4.5
      gemfile: gemfiles/rails_6.0.gemfile
    - rvm: 2.5.5
      gemfile: gemfiles/rails_4.0.gemfile
    - rvm: 2.5.5
      gemfile: gemfiles/rails_4.1.gemfile
    - rvm: 2.6.2
      gemfile: gemfiles/rails_4.0.gemfile
    - rvm: 2.6.2
      gemfile: gemfiles/rails_4.1.gemfile
    - rvm: 2.6.2
      gemfile: gemfiles/rails_4.2.gemfile

services:
  - docker

before_install:
  - docker-compose up -d
  - bundle update --bundler

script:
  - bundle exec rake spec
