name: Active Record Multi-Tenant Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.0'
          - '3.1'
          - '3.2'
        gemfile:
          - rails_6.0
          - rails_6.1
          - rails_7.0
          - active_record_6.0
          - active_record_6.1
          - active_record_7.0
        citus_version:
          - '10'
          - '11'
        
    name: Rb:${{ matrix.ruby }}/${{ matrix.gemfile }} / Cts ${{ matrix.citus_version }}
    env:
       BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
       CITUS_VERSION: ${{ matrix.citus_version }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          docker-compose up -d
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: |
          bundle exec rake spec

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
